[workspace]
resolver = "2"
members = [
    "lib",
    "primitives",
    # "raiko-guests/sgx",
    # "raiko-guests/risc0",
    # "raiko-guests/powdr",
    # "raiko-guests/succinct",
    "raiko-host",
    "sgx-ra",
    "tests/*",
]


# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3



[workspace.dependencies]
bonsai-sdk = "0.5"
hashbrown = { version = "0.14", features = ["inline-more"] }
risc0-build = "0.19"
risc0-zkvm = { version = "0.19", default-features = false }
revm-primitives = { git = "https://github.com/ceciliaz030/revm.git", branch = "sync-taiko-v3.5", default_features = false }
revm = { git = "https://github.com/ceciliaz030/revm.git", branch = "sync-taiko-v3.5", default-features = false, features = ["serde"] }

