[workspace]
resolver = "2"
members = ["guests", "host", "lib", "primitives", "testing/ef-tests"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[patch.crates-io]
# use optimized risc0 circuit
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risc0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.1-risc0" }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }
revm = { git = "https://github.com/johntaiko/revm", branch = "feat/taiko" }
revm-primitives = { git = "https://github.com/johntaiko/revm", branch = "feat/taiko" }
revm-interpreter = { git = "https://github.com/johntaiko/revm", branch = "feat/taiko" }
revm-precompile = { git = "https://github.com/johntaiko/revm", branch = "feat/taiko" }


[workspace.dependencies]
bonsai-sdk = "0.4"
hashbrown = { version = "0.14", features = ["inline-more"] }
risc0-build = "0.18"
risc0-zkvm = { version = "0.18", default-features = false }
revm = { version = "3.5", default-features = false, features = [
  "std",
  "serde",
  "optional_no_base_fee",
  "optional_balance_check",
] }
