[workspace]
resolver = "2"
members = [
    "guests",
    "host",
    "lib",
    "primitives",
    "testing/ef-tests"
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[workspace.dependencies]
bonsai-sdk = "0.4"
hashbrown = { version = "0.14", features = ["inline-more"] }
risc0-build = "0.18"
risc0-zkvm = { version = "0.18", default-features = false }
revm = { git = "https://github.com/bluealloy/revm.git", default-features = false, features = ["std", "serde", "optimism"] }
