[package]
name = "powdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
driver-common = { version = "0.1.0", path = "../common" }
serde_cbor = "0.11.2"
tokio = "1.36.0"
