[package]
name = "bin-powdr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powdr = { git = "https://github.com/powdr-labs/powdr", branch = "continuations-data-input" }
env_logger = "0.10.0"
